### ISSUE TITLE
Would it be possible to create a new release?

### ISSUE THREAD

**Issue by franciscoj** [dhui/dktest#14]
Hi!

#13 upgraded containerd, which contained this security warning https://github.com/containerd/containerd/security/advisories/GHSA-crp2-qrr5-8pq7

Would it be possible to create a new release so that other projects like https://github.com/golang-migrate/migrate can update as well?

I'd be happy to contribute the PR to https://github.com/golang-migrate/migrate myself if needed :)

Thanks!

**Comment by dhui** [comment]
Released [v0.3.10](https://github.com/dhui/dktest/releases/tag/v0.3.10) which contains the security fixes. I'll update migrate as well

**Comment by franciscoj** [comment]
Thanks a lot!
