### ISSUE TITLE
Please update docker/docker

### ISSUE THREAD

**Issue by ernsheong** [dhui/dktest#5]
```
$ go mod tidy
go: <MY_PROJECT> imports
        github.com/golang-migrate/migrate/v4/database/postgres tested by
        github.com/golang-migrate/migrate/v4/database/postgres.test imports
        github.com/dhui/dktest imports
        github.com/docker/docker/pkg/jsonmessage imports
        github.com/docker/docker/pkg/term imports
        github.com/docker/docker/pkg/term/windows imports
        github.com/Sirupsen/logrus: github.com/Sirupsen/logrus@v1.6.0: parsing go.mod:
        module declares its path as: github.com/sirupsen/logrus
                but was required as: github.com/Sirupsen/logrus
```

I believe to fix this you need to update `docker/docker` and make a new release, then upstream can update and fix this problem. Thanks a lot!

**Comment by dhui** [comment]
I think you have another dependency which uses a broken version of `docker/docker`

```shell
$ grep logrus go.mod  # migrate's go.mod file
	github.com/sirupsen/logrus v1.2.0 // indirect
```

**Comment by deathtrix** [comment]
Actually he's right. https://github.com/moby/moby/blob/19.03/pkg/term/windows/windows.go
They updated to lower case in 19.03, so please update docker/docker.

**Comment by yellowred** [comment]
seems to be pointing to the dktest:
```
➜ go mod tidy
go: finding module for package github.com/docker/docker/api/types/image
XYZ imports
	github.com/golang-migrate/migrate/v4/database/postgres tested by
	github.com/golang-migrate/migrate/v4/database/postgres.test imports
	github.com/dhui/dktest tested by
	github.com/dhui/dktest.test imports
	github.com/dhui/dktest/mockdockerclient imports
	github.com/docker/docker/api/types/image: module github.com/docker/docker@latest found (v1.13.1), but does not contain package github.com/docker/docker/api/types/image
```

**Comment by veqryn** [comment]
I see you've made a commit to fix this. Can you please merge and make a new release? I am running into the same go mod errors as everyone else.

**Comment by dhui** [comment]
Unfortunately, [builds are failing](https://travis-ci.org/github/dhui/dktest/builds/726738440), so I can't merge [my changes](https://github.com/dhui/dktest/compare/update_docker). The new docker client/sdk is causing tests to hang and I haven't been able figured out why. Any help is appreciated! 🙏

**Comment by deathtrix** [comment]
have you try adding travis_wait as a prefix to line 38 of .travis.yml ?

**Comment by dhui** [comment]
> have you try adding travis_wait as a prefix to line 38 of .travis.yml ?

Increasing the TravisCI wait time won't help as the issue has nothing to do with TravisCI

**Comment by ankur22** [comment]
The solution seems to be to use `POSTGRES_HOST_AUTH_METHOD: trust` in the example postgres test. I opened a ticket https://github.com/dhui/dktest/pull/6 incase it helps.

**Comment by dhui** [comment]
Fixed in [v0.3.3](https://github.com/dhui/dktest/releases/tag/v0.3.3)

**Comment by veqryn** [comment]
@dhui thank you. Can you please make new versioned release of https://github.com/golang-migrate/migrate ?

**Comment by dhui** [comment]
Release [v4.14.0](https://github.com/golang-migrate/migrate/releases/tag/v4.14.0)
